// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Public values — safe to ship in the bundle (anon key by design)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://qqpmmehdowmsprkfhfle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxcG1tZWhkb3dtc3Bya2ZoZmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4NDg0OTYsImV4cCI6MjA4MjQyNDQ5Nn0.QdRleCAv0GDCsqStlt3kxizkngGaz5OP0F9C8zlcVGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});